// Generated by scripts/generate-clients.mjs. Do not edit.
export const CONTEXT_CONTRACT_VERSION = '1.2.0';
export const CONTEXT_DEFAULT_BASE_URL = 'https://www.feason.com';
export const contextOperations = {
  manifest: { method: 'GET', path: '/api/context/v1/manifest' },
  contextualize: { method: 'POST', path: '/api/context/v1/contextualize' },
  evaluateClaim: { method: 'POST', path: '/api/context/v1/evaluate-claim' },
  search: { method: 'POST', path: '/api/context/v1/search' },
  evidencePacket: { method: 'POST', path: '/api/context/v1/evidence-packet' },
  verifyCitation: { method: 'POST', path: '/api/context/v1/verify-citation' },
} as const;
export type ContextOperationName = keyof typeof contextOperations;
