import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const repositoryRoot = resolve(import.meta.dirname, '..');
const checkOnly = process.argv.includes('--check');
const contract = JSON.parse(await readFile(resolve(repositoryRoot, 'contract.json'), 'utf8'));
validateContract(contract);

const outputs = new Map([
  [resolve(repositoryRoot, 'typescript/generated.ts'), typescriptOutput(contract)],
  [resolve(repositoryRoot, 'python/feason_context/_generated.py'), pythonOutput(contract)],
]);

for (const [file, expected] of outputs) {
  if (checkOnly) {
    const actual = await readFile(file, 'utf8').catch(() => '');
    if (actual !== expected) throw new Error(`${file} is stale; run npm run generate`);
  } else {
    await writeFile(file, expected);
  }
}

await verifyVersions(contract);
await verifyOpenApi(contract);
console.log(checkOnly ? 'Feason Context generated clients and release metadata are current.' : 'Generated Feason Context clients.');

function validateContract(value) {
  if (!value || typeof value !== 'object' || !semver(value.contractVersion) || !semver(value.sdkVersion)) {
    throw new Error('contract.json requires semantic contractVersion and sdkVersion values');
  }
  if (typeof value.baseUrl !== 'string' || !value.baseUrl.startsWith('https://')) throw new Error('Contract baseUrl must be HTTPS');
  const operations = Object.entries(value.operations ?? {});
  if (!operations.length) throw new Error('Contract requires operations');
  for (const [name, operation] of operations) {
    if (!/^[a-z][A-Za-z]+$/.test(name) || !['GET', 'POST'].includes(operation?.method)
      || typeof operation?.path !== 'string' || !operation.path.startsWith('/api/context/v1/')) {
      throw new Error(`Invalid SDK operation: ${name}`);
    }
  }
}

function typescriptOutput(value) {
  const rows = Object.entries(value.operations).map(([name, operation]) =>
    `  ${name}: { method: '${operation.method}', path: '${operation.path}' },`).join('\n');
  return `// Generated by scripts/generate-clients.mjs. Do not edit.\nexport const CONTEXT_CONTRACT_VERSION = '${value.contractVersion}';\nexport const CONTEXT_DEFAULT_BASE_URL = '${value.baseUrl}';\nexport const contextOperations = {\n${rows}\n} as const;\nexport type ContextOperationName = keyof typeof contextOperations;\n`;
}

function pythonOutput(value) {
  const rows = Object.entries(value.operations).map(([name, operation]) =>
    `    "${name}": {"method": "${operation.method}", "path": "${operation.path}"},`).join('\n');
  return `"""Generated package metadata. Do not edit directly."""\n\nCONTEXT_CONTRACT_VERSION = "${value.contractVersion}"\nCONTEXT_DEFAULT_BASE_URL = "${value.baseUrl}"\nOPERATIONS = {\n${rows}\n}\n`;
}

async function verifyVersions(value) {
  const npmPackage = JSON.parse(await readFile(resolve(repositoryRoot, 'typescript/package.json'), 'utf8'));
  const pyproject = await readFile(resolve(repositoryRoot, 'python/pyproject.toml'), 'utf8');
  const pythonVersion = pyproject.match(/^version = "([^"]+)"$/m)?.[1];
  if (npmPackage.version !== value.sdkVersion || pythonVersion !== value.sdkVersion) {
    throw new Error(`SDK versions must all equal ${value.sdkVersion}`);
  }
  const requestedTag = process.env.GITHUB_REF_NAME;
  if (requestedTag?.startsWith('context-sdk-v') && requestedTag !== `context-sdk-v${value.sdkVersion}`) {
    throw new Error(`Release tag ${requestedTag} does not match SDK version ${value.sdkVersion}`);
  }
}

async function verifyOpenApi(value) {
  const openapi = await readFile(resolve(repositoryRoot, 'openapi/feason-context-openapi.yaml'), 'utf8');
  for (const operation of Object.values(value.operations)) {
    const escaped = operation.path.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    const method = operation.method.toLowerCase();
    if (!new RegExp(`^  ${escaped}:\\n    ${method}:`, 'm').test(openapi)) {
      throw new Error(`OpenAPI contract is missing ${operation.method} ${operation.path}`);
    }
  }
}

function semver(value) {
  return typeof value === 'string' && /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(value);
}
